// StyleKit Style Definition
// Generated by style-extractor v2.0
// Source: {{SOURCE_URL}}
// Generated at: {{TIMESTAMP}}

import type { StyleDefinition } from '@/lib/styles/types';

/**
 * {{PROJECT_NAME}} Style
 *
 * Extracted from {{SOURCE_URL}}
 *
 * Design Philosophy:
 * {{DESIGN_PHILOSOPHY}}
 *
 * Key Characteristics:
 * - {{CHARACTERISTIC_1}}
 * - {{CHARACTERISTIC_2}}
 * - {{CHARACTERISTIC_3}}
 */
export const {{STYLE_ID}}Style: StyleDefinition = {
  id: '{{STYLE_ID}}',
  name: '{{PROJECT_NAME}}',
  description: '{{DESCRIPTION}}',

  // ===========================================
  // Colors
  // ===========================================
  colors: {
    // Brand / Semantic
    primary: '{{COLOR_PRIMARY}}',
    secondary: '{{COLOR_SECONDARY}}',
    accent: '{{COLOR_ACCENT}}',

    // Surfaces
    background: '{{COLOR_BACKGROUND}}',
    surface: '{{COLOR_SURFACE}}',
    surfaceAlt: '{{COLOR_SURFACE_ALT}}',

    // Text
    text: '{{COLOR_TEXT}}',
    textMuted: '{{COLOR_TEXT_MUTED}}',
    textInverse: '{{COLOR_TEXT_INVERSE}}',

    // Borders
    border: '{{COLOR_BORDER}}',
    borderMuted: '{{COLOR_BORDER_MUTED}}',

    // Semantic States
    error: '{{COLOR_ERROR}}',
    success: '{{COLOR_SUCCESS}}',
    warning: '{{COLOR_WARNING}}',
    info: '{{COLOR_INFO}}',
  },

  // ===========================================
  // Typography
  // ===========================================
  typography: {
    fontFamily: {
      primary: '{{FONT_PRIMARY}}',
      secondary: '{{FONT_SECONDARY}}',
      mono: '{{FONT_MONO}}',
    },

    fontSize: {
      xs: '{{FONT_SIZE_XS}}',
      sm: '{{FONT_SIZE_SM}}',
      base: '{{FONT_SIZE_BASE}}',
      lg: '{{FONT_SIZE_LG}}',
      xl: '{{FONT_SIZE_XL}}',
      '2xl': '{{FONT_SIZE_2XL}}',
      '3xl': '{{FONT_SIZE_3XL}}',
      '4xl': '{{FONT_SIZE_4XL}}',
    },

    fontWeight: {
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
    },

    lineHeight: {
      tight: {{LINE_HEIGHT_TIGHT}},
      normal: {{LINE_HEIGHT_NORMAL}},
      relaxed: {{LINE_HEIGHT_RELAXED}},
    },
  },

  // ===========================================
  // Spacing
  // ===========================================
  spacing: {
    xs: '{{SPACING_XS}}',
    sm: '{{SPACING_SM}}',
    md: '{{SPACING_MD}}',
    lg: '{{SPACING_LG}}',
    xl: '{{SPACING_XL}}',
    '2xl': '{{SPACING_2XL}}',
    '3xl': '{{SPACING_3XL}}',
    '4xl': '{{SPACING_4XL}}',
  },

  // ===========================================
  // Borders
  // ===========================================
  borders: {
    width: {
      thin: '1px',
      default: '2px',
      thick: '4px',
    },

    radius: {
      none: '0',
      sm: '{{RADIUS_SM}}',
      default: '{{RADIUS_DEFAULT}}',
      lg: '{{RADIUS_LG}}',
      xl: '{{RADIUS_XL}}',
      full: '9999px',
    },
  },

  // ===========================================
  // Shadows
  // ===========================================
  shadows: {
    none: 'none',
    sm: '{{SHADOW_SM}}',
    default: '{{SHADOW_DEFAULT}}',
    md: '{{SHADOW_MD}}',
    lg: '{{SHADOW_LG}}',
    xl: '{{SHADOW_XL}}',
  },

  // ===========================================
  // Motion
  // ===========================================
  motion: {
    duration: {
      instant: '{{DURATION_INSTANT}}',
      fast: '{{DURATION_FAST}}',
      normal: '{{DURATION_NORMAL}}',
      slow: '{{DURATION_SLOW}}',
      slower: '{{DURATION_SLOWER}}',
    },

    easing: {
      linear: 'linear',
      ease: 'ease',
      easeIn: 'ease-in',
      easeOut: 'ease-out',
      easeInOut: 'ease-in-out',
      emphasis: '{{EASING_EMPHASIS}}',
    },

    // Extracted keyframes
    keyframes: {
      // Add extracted keyframes here
    },
  },

  // ===========================================
  // Components
  // ===========================================
  components: {
    button: {
      base: {
        padding: '{{BUTTON_PADDING}}',
        borderRadius: '{{BUTTON_RADIUS}}',
        fontSize: '{{BUTTON_FONT_SIZE}}',
        fontWeight: 500,
        transition: 'all {{DURATION_FAST}} ease',
      },
      variants: {
        primary: {
          background: '{{COLOR_PRIMARY}}',
          color: '{{COLOR_TEXT_INVERSE}}',
          hover: {
            background: '{{COLOR_PRIMARY_HOVER}}',
          },
        },
        secondary: {
          background: '{{COLOR_SURFACE}}',
          color: '{{COLOR_TEXT}}',
          border: '1px solid {{COLOR_BORDER}}',
        },
        ghost: {
          background: 'transparent',
          color: '{{COLOR_TEXT}}',
        },
      },
    },

    card: {
      base: {
        background: '{{COLOR_SURFACE}}',
        borderRadius: '{{CARD_RADIUS}}',
        padding: '{{CARD_PADDING}}',
        border: '1px solid {{COLOR_BORDER}}',
      },
      hover: {
        shadow: '{{SHADOW_MD}}',
        transform: 'translateY(-2px)',
      },
    },

    input: {
      base: {
        background: '{{COLOR_BACKGROUND}}',
        border: '1px solid {{COLOR_BORDER}}',
        borderRadius: '{{INPUT_RADIUS}}',
        padding: '{{INPUT_PADDING}}',
        fontSize: '{{FONT_SIZE_BASE}}',
      },
      focus: {
        borderColor: '{{COLOR_PRIMARY}}',
        shadow: '0 0 0 2px {{COLOR_PRIMARY}}20',
      },
    },
  },
};

export default {{STYLE_ID}}Style;

// ===========================================
// CSS Variables Export
// ===========================================
export const {{STYLE_ID}}CSSVariables = `
:root {
  /* Colors */
  --color-primary: ${{{STYLE_ID}}Style.colors.primary};
  --color-secondary: ${{{STYLE_ID}}Style.colors.secondary};
  --color-accent: ${{{STYLE_ID}}Style.colors.accent};
  --color-background: ${{{STYLE_ID}}Style.colors.background};
  --color-surface: ${{{STYLE_ID}}Style.colors.surface};
  --color-text: ${{{STYLE_ID}}Style.colors.text};
  --color-text-muted: ${{{STYLE_ID}}Style.colors.textMuted};
  --color-border: ${{{STYLE_ID}}Style.colors.border};

  /* Typography */
  --font-primary: ${{{STYLE_ID}}Style.typography.fontFamily.primary};
  --font-secondary: ${{{STYLE_ID}}Style.typography.fontFamily.secondary};
  --font-mono: ${{{STYLE_ID}}Style.typography.fontFamily.mono};

  /* Spacing */
  --space-xs: ${{{STYLE_ID}}Style.spacing.xs};
  --space-sm: ${{{STYLE_ID}}Style.spacing.sm};
  --space-md: ${{{STYLE_ID}}Style.spacing.md};
  --space-lg: ${{{STYLE_ID}}Style.spacing.lg};
  --space-xl: ${{{STYLE_ID}}Style.spacing.xl};

  /* Motion */
  --duration-fast: ${{{STYLE_ID}}Style.motion.duration.fast};
  --duration-normal: ${{{STYLE_ID}}Style.motion.duration.normal};
  --duration-slow: ${{{STYLE_ID}}Style.motion.duration.slow};
}
`;
